language: python
python:
 - "2.7"

notifications:
    email: false

install:
    - pip install -r requirements/local.txt --use-mirrors

script:
    - python manage.py syncdb --settings=core.settings.test
    - python manage.py migrate --settings=core.settings.test
    - python manage.py test projects hosts accounts --settings=core.settings.test
