#! lua

-- check tcp socket
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

-- do check
function check(opts) 
  local socket = require("socket")
  t1 = socket.gettime()
  client = socket.tcp()
  client:settimeout(6)
  ok,err = client:connect(opts["H"], opts["p"])
  t2 = socket.gettime()
  if not ok then
    print("CRITICAL - "..err.."\n")
    return STATUS_CRITICAL
  end
  escaped_time = (t2 - t1) * 1000
  print(string.format("Port %s OK - response time: %.2fms\n", 
    opts["p"], escaped_time))
  print(string.format("metric:time: %.3fms", escaped_time))
  return STATUS_OK
end

-- usage
function usage() 
  print("Usage: check_tcp -H Host -p Port")
  os.exit(0)
end

-- parse arguments
local long_opts = {
   help    = "h",
   host    = "H",
   port	   = "p",
}

local opts,optind = getopts(arg, "hH:p:", long_opts)
if not opts["H"] then
  print("UNKNOWN - miss argument 'host'\n")
  usage()
end
if not opts["p"] then
  print("UNKNOWN - miss argument 'port'\n")
  usage()
end

status=check(opts)

os.exit(status)

